### ISSUE TITLE
Projectiles are not stopped in item room

### ISSUE THREAD

**Issue by andrew454** [Jkim-Hack/cse3902#209]
The walls do not collide with items in Item room. Some play testing may need to look at behavior of projectiles in Item Room

**Comment by PranavKoduri** [comment]
Item room doesn't contain walls so there are no wall collidables.

We could make a new type of block that is the same as a normal block except it uses wall collidables instead of block collidables, and then change the bricks in the item room from normal blocks to the new block type. But there are keese in the room, so that would stop them from freely moving around the item room, so that won't work.

A new type of collidable may have to be made where it stops projectiles, but keese can still pass through.

**Comment by alexbook45** [comment]
Fixing this should also fix keese leaving the item room
